[project]
name = "xbow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-openai>=1.0.2",
    "langgraph[agent]>=1.0.2",
]
